//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BehaviorPB.proto
namespace BehaviorPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Selector")]
  public partial class Selector : global::ProtoBuf.IExtensible
  {
    public Selector() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Sequence")]
  public partial class Sequence : global::ProtoBuf.IExtensible
  {
    public Sequence() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Parallel")]
  public partial class Parallel : global::ProtoBuf.IExtensible
  {
    public Parallel() {}
    
    private BehaviorPB.ParallelPolicy _policy;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"policy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BehaviorPB.ParallelPolicy policy
    {
      get { return _policy; }
      set { _policy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Action")]
  public partial class Action : global::ProtoBuf.IExtensible
  {
    public Action() {}
    
    private string _script_path;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"script_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string script_path
    {
      get { return _script_path; }
      set { _script_path = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Null", Value=0)]
      Null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CntTest2_2", Value=992)]
      CntTest2_2 = 992,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CntTest0", Value=993)]
      CntTest0 = 993,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CntTest1", Value=994)]
      CntTest1 = 994,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CntTest2", Value=995)]
      CntTest2 = 995,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CntTest", Value=996)]
      CntTest = 996,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Printf", Value=999)]
      Printf = 999
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Condition")]
  public partial class Condition : global::ProtoBuf.IExtensible
  {
    public Condition() {}
    
    private string _script_path;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"script_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string script_path
    {
      get { return _script_path; }
      set { _script_path = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Null", Value=0)]
      Null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Printf", Value=998)]
      Printf = 998
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Link")]
  public partial class Link : global::ProtoBuf.IExtensible
  {
    public Link() {}
    
    private string _sub_tree_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sub_tree_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sub_tree_name
    {
      get { return _sub_tree_name; }
      set { _sub_tree_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DecoratorNot")]
  public partial class DecoratorNot : global::ProtoBuf.IExtensible
  {
    public DecoratorNot() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DecoratorLoop")]
  public partial class DecoratorLoop : global::ProtoBuf.IExtensible
  {
    public DecoratorLoop() {}
    
    private int _loop_cnt;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"loop_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int loop_cnt
    {
      get { return _loop_cnt; }
      set { _loop_cnt = value; }
    }
    private string _bb_loop_key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bb_loop_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string bb_loop_key
    {
      get { return _bb_loop_key; }
      set { _bb_loop_key = value; }
    }
    private string _bb_i;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bb_i", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string bb_i
    {
      get { return _bb_i; }
      set { _bb_i = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DecoratorCounter")]
  public partial class DecoratorCounter : global::ProtoBuf.IExtensible
  {
    public DecoratorCounter() {}
    
    private int _limit_cnt;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"limit_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int limit_cnt
    {
      get { return _limit_cnt; }
      set { _limit_cnt = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Type")]
    public enum Type
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Null", Value=0)]
      Null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Printf", Value=997)]
      Printf = 997
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DecoratorTimer")]
  public partial class DecoratorTimer : global::ProtoBuf.IExtensible
  {
    public DecoratorTimer() {}
    
    private int _elpase;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"elpase", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int elpase
    {
      get { return _elpase; }
      set { _elpase = value; }
    }
    private int _start;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int start
    {
      get { return _start; }
      set { _start = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DecoratorRand")]
  public partial class DecoratorRand : global::ProtoBuf.IExtensible
  {
    public DecoratorRand() {}
    
    private int _r_idx;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"r_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int r_idx
    {
      get { return _r_idx; }
      set { _r_idx = value; }
    }
    private int _r_begin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"r_begin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int r_begin
    {
      get { return _r_begin; }
      set { _r_begin = value; }
    }
    private int _r_end;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"r_end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int r_end
    {
      get { return _r_end; }
      set { _r_end = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _choose_arr = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"choose_arr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> choose_arr
    {
      get { return _choose_arr; }
    }
  
    private string _bb_rnd;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"bb_rnd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string bb_rnd
    {
      get { return _bb_rnd; }
      set { _bb_rnd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Node")]
  public partial class Node : global::ProtoBuf.IExtensible
  {
    public Node() {}
    

    private BehaviorPB.Node.Editor _editor = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"editor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Node.Editor editor
    {
      get { return _editor; }
      set { _editor = value; }
    }
    private readonly global::System.Collections.Generic.List<BehaviorPB.Node> _nodes = new global::System.Collections.Generic.List<BehaviorPB.Node>();
    [global::ProtoBuf.ProtoMember(2, Name=@"nodes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BehaviorPB.Node> nodes
    {
      get { return _nodes; }
    }
  
    private BehaviorPB.NodeType _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BehaviorPB.NodeType type
    {
      get { return _type; }
      set { _type = value; }
    }

    private BehaviorPB.Selector _selector = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"selector", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Selector selector
    {
      get { return _selector; }
      set { _selector = value; }
    }

    private BehaviorPB.Sequence _sequence = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Sequence sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }

    private BehaviorPB.Parallel _parallel = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"parallel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Parallel parallel
    {
      get { return _parallel; }
      set { _parallel = value; }
    }

    private BehaviorPB.Action _action = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Action action
    {
      get { return _action; }
      set { _action = value; }
    }

    private BehaviorPB.Condition _condition = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"condition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Condition condition
    {
      get { return _condition; }
      set { _condition = value; }
    }

    private BehaviorPB.Link _link = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"link", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Link link
    {
      get { return _link; }
      set { _link = value; }
    }

    private BehaviorPB.DecoratorNot _d_not = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"d_not", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.DecoratorNot d_not
    {
      get { return _d_not; }
      set { _d_not = value; }
    }

    private BehaviorPB.DecoratorLoop _d_loop = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"d_loop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.DecoratorLoop d_loop
    {
      get { return _d_loop; }
      set { _d_loop = value; }
    }

    private BehaviorPB.DecoratorCounter _d_counter = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"d_counter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.DecoratorCounter d_counter
    {
      get { return _d_counter; }
      set { _d_counter = value; }
    }

    private BehaviorPB.DecoratorTimer _d_timer = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"d_timer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.DecoratorTimer d_timer
    {
      get { return _d_timer; }
      set { _d_timer = value; }
    }

    private BehaviorPB.DecoratorRand _d_rand = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"d_rand", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.DecoratorRand d_rand
    {
      get { return _d_rand; }
      set { _d_rand = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Editor")]
  public partial class Editor : global::ProtoBuf.IExtensible
  {
    public Editor() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tree")]
  public partial class Tree : global::ProtoBuf.IExtensible
  {
    public Tree() {}
    

    private BehaviorPB.Tree.Editor _editor = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"editor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Tree.Editor editor
    {
      get { return _editor; }
      set { _editor = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private BehaviorPB.Node _root;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"root", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BehaviorPB.Node root
    {
      get { return _root; }
      set { _root = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Editor")]
  public partial class Editor : global::ProtoBuf.IExtensible
  {
    public Editor() {}
    
    private string _desc;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"NodeType")]
    public enum NodeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Null", Value=0)]
      NodeType_Null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Selector", Value=1)]
      NodeType_Selector = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Sequence", Value=2)]
      NodeType_Sequence = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Parallel", Value=3)]
      NodeType_Parallel = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Action", Value=4)]
      NodeType_Action = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Condition", Value=5)]
      NodeType_Condition = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Link", Value=6)]
      NodeType_Link = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Decorator", Value=7)]
      NodeType_Decorator = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_DecoratorNot", Value=8)]
      NodeType_DecoratorNot = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_DecoratorLoop", Value=9)]
      NodeType_DecoratorLoop = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_DecoratorCounter", Value=10)]
      NodeType_DecoratorCounter = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_DecoratorTimer", Value=11)]
      NodeType_DecoratorTimer = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_DecoratorRand", Value=12)]
      NodeType_DecoratorRand = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_CntTestAction2_2", Value=992)]
      NodeType_CntTestAction2_2 = 992,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_CntTestAction0", Value=993)]
      NodeType_CntTestAction0 = 993,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_CntTestAction1", Value=994)]
      NodeType_CntTestAction1 = 994,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_CntTestAction2", Value=995)]
      NodeType_CntTestAction2 = 995,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_CntTestAction", Value=996)]
      NodeType_CntTestAction = 996,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_PrintfDecoratorCounter", Value=997)]
      NodeType_PrintfDecoratorCounter = 997,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_PrintfCondtion", Value=998)]
      NodeType_PrintfCondtion = 998,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_PrintfAction", Value=999)]
      NodeType_PrintfAction = 999
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ParallelPolicy")]
    public enum ParallelPolicy
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ParallelPolicy_FailOnAll", Value=0)]
      ParallelPolicy_FailOnAll = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ParallelPolicy_SuccOnAll", Value=1)]
      ParallelPolicy_SuccOnAll = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ParallelPolicy_FailAlways", Value=2)]
      ParallelPolicy_FailAlways = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ParallelPolicy_SuccAlways", Value=3)]
      ParallelPolicy_SuccAlways = 3
    }
  
}