//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: BehaviorPB.proto
namespace BehaviorPB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Selector")]
  public partial class Selector : global::ProtoBuf.IExtensible
  {
    public Selector() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Sequence")]
  public partial class Sequence : global::ProtoBuf.IExtensible
  {
    public Sequence() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Parallel")]
  public partial class Parallel : global::ProtoBuf.IExtensible
  {
    public Parallel() {}
    
    private int _policy;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"policy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int policy
    {
      get { return _policy; }
      set { _policy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Action")]
  public partial class Action : global::ProtoBuf.IExtensible
  {
    public Action() {}
    
    private string _script_path;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"script_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string script_path
    {
      get { return _script_path; }
      set { _script_path = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Condition")]
  public partial class Condition : global::ProtoBuf.IExtensible
  {
    public Condition() {}
    
    private string _script_path;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"script_path", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string script_path
    {
      get { return _script_path; }
      set { _script_path = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Link")]
  public partial class Link : global::ProtoBuf.IExtensible
  {
    public Link() {}
    
    private string _sub_tree_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sub_tree_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sub_tree_name
    {
      get { return _sub_tree_name; }
      set { _sub_tree_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DecoratorNot")]
  public partial class DecoratorNot : global::ProtoBuf.IExtensible
  {
    public DecoratorNot() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DecoratorLoop")]
  public partial class DecoratorLoop : global::ProtoBuf.IExtensible
  {
    public DecoratorLoop() {}
    
    private int _loop_cnt;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"loop_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int loop_cnt
    {
      get { return _loop_cnt; }
      set { _loop_cnt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DecoratorCounter")]
  public partial class DecoratorCounter : global::ProtoBuf.IExtensible
  {
    public DecoratorCounter() {}
    
    private int _limit_cnt;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"limit_cnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int limit_cnt
    {
      get { return _limit_cnt; }
      set { _limit_cnt = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DecoratorTimer")]
  public partial class DecoratorTimer : global::ProtoBuf.IExtensible
  {
    public DecoratorTimer() {}
    
    private int _elpase;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"elpase", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int elpase
    {
      get { return _elpase; }
      set { _elpase = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Node")]
  public partial class Node : global::ProtoBuf.IExtensible
  {
    public Node() {}
    

    private BehaviorPB.Node.Editor _editor = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"editor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Node.Editor editor
    {
      get { return _editor; }
      set { _editor = value; }
    }
    private readonly global::System.Collections.Generic.List<BehaviorPB.Node> _nodes = new global::System.Collections.Generic.List<BehaviorPB.Node>();
    [global::ProtoBuf.ProtoMember(2, Name=@"nodes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BehaviorPB.Node> nodes
    {
      get { return _nodes; }
    }
  
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }

    private BehaviorPB.Selector _selector = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"selector", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Selector selector
    {
      get { return _selector; }
      set { _selector = value; }
    }

    private BehaviorPB.Sequence _sequence = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Sequence sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }

    private BehaviorPB.Parallel _parallel = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"parallel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Parallel parallel
    {
      get { return _parallel; }
      set { _parallel = value; }
    }

    private BehaviorPB.Action _action = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"action", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Action action
    {
      get { return _action; }
      set { _action = value; }
    }

    private BehaviorPB.Condition _condition = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"condition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Condition condition
    {
      get { return _condition; }
      set { _condition = value; }
    }

    private BehaviorPB.Link _link = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"link", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Link link
    {
      get { return _link; }
      set { _link = value; }
    }

    private BehaviorPB.DecoratorNot _d_not = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"d_not", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.DecoratorNot d_not
    {
      get { return _d_not; }
      set { _d_not = value; }
    }

    private BehaviorPB.DecoratorLoop _d_loop = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"d_loop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.DecoratorLoop d_loop
    {
      get { return _d_loop; }
      set { _d_loop = value; }
    }

    private BehaviorPB.DecoratorCounter _d_counter = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"d_counter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.DecoratorCounter d_counter
    {
      get { return _d_counter; }
      set { _d_counter = value; }
    }

    private BehaviorPB.DecoratorTimer _d_timer = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"d_timer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.DecoratorTimer d_timer
    {
      get { return _d_timer; }
      set { _d_timer = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Editor")]
  public partial class Editor : global::ProtoBuf.IExtensible
  {
    public Editor() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _desc;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tree")]
  public partial class Tree : global::ProtoBuf.IExtensible
  {
    public Tree() {}
    

    private BehaviorPB.Tree.Editor _editor = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"editor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public BehaviorPB.Tree.Editor editor
    {
      get { return _editor; }
      set { _editor = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private BehaviorPB.Node _root;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"root", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public BehaviorPB.Node root
    {
      get { return _root; }
      set { _root = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Editor")]
  public partial class Editor : global::ProtoBuf.IExtensible
  {
    public Editor() {}
    
    private string _desc;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"NodeType")]
    public enum NodeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Null", Value=0)]
      NodeType_Null = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Selector", Value=1)]
      NodeType_Selector = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Sequence", Value=2)]
      NodeType_Sequence = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Parallel", Value=3)]
      NodeType_Parallel = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Action", Value=4)]
      NodeType_Action = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Condition", Value=5)]
      NodeType_Condition = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Link", Value=6)]
      NodeType_Link = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_Decorator", Value=7)]
      NodeType_Decorator = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_DecoratorNot", Value=8)]
      NodeType_DecoratorNot = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_DecoratorLoop", Value=9)]
      NodeType_DecoratorLoop = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_DecoratorCounter", Value=10)]
      NodeType_DecoratorCounter = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_DecoratorTimer", Value=11)]
      NodeType_DecoratorTimer = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_PrintfDecoratorCounter", Value=997)]
      NodeType_PrintfDecoratorCounter = 997,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_PrintfCondtion", Value=998)]
      NodeType_PrintfCondtion = 998,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NodeType_PrintfAction", Value=999)]
      NodeType_PrintfAction = 999
    }
  
}